
module.exports = {
	"text001.png": "Votre colis est livré.",
	"text002.png": "Votre colis est prêt à être livré",
	"text003.png": "Votre colis est sorti de la douane.",
	"text005.png": "STATION TOTAL ACCESS",
	"text006.png": "Votre colis est disponible chez le commerçant sélectionné. Le destinataire dispose de 10 jours ouvrables pour retirer son colis sur présentation d'une pièce d'identité et du bon de retrait.",
	"text007.png": "CHRONOPOST RENNES",
	"text008.png": "Plate-forme Sud-Ouest",
	"text011.png": "ABIDJAN (IVORY COST)",
	"text012.png": "ABIDJAN (IVORY COST)",
	"text015.png": "Votre colis a quitté le territoire",
	"text016.png": "SODEXI",
	"text017.png": "EXPRESS SODEXI",
	"text018.png": "GEOPOST SAS C/O SODEXI DEPOT",
	"text019.png": "Bureau de Poste Orleans",
	"text020.png": "Agence Seine-Saint-Denis",
	"text021.png": "Plate-forme Ile-de-France Nord",
	"text023.png": "Votre colis est livré.",
	"text024.png": "Votre colis est prêt à être livré",
	"text022.png": "Plate-forme Sud-Ouest",
	"text004.png": "Votre colis est arrivé sur son site de distribution",
	"text009.png": "Votre colis est pris en charge par La Poste, il est en cours d'acheminement.",
	"text010.png": "Votre colis n'a pas encore été remis à La Poste par l'expediteur.",
	"text013.png": "Votre colis est retenu par nos services dans l'attente de son dédouanement.",
	"text014.png": "Votre colis est arrivé dans le pays de destination",
	"text025.png": "Votre colis est arrivé sur son site de distribution",
	"text026.png": "Votre colis est pris en charge par La Poste. Il est en cours d'acheminement",
	"text027.png": "Votre colis n'a pas encore été remis à La Poste par l'expediteur.",
	"text028.png": "Agence Seine-Saint-Denis",
	"text029.png": "Plate-forme Ile-de-France Nord",
	"text030.png": "Plate-forme Rhône-Alpes",
	"text031.png": "Votre colis est arrivé dans le pays de destination",
	"text032.png": "Plate-forme Rhône-Alpes",
	"text033.png": "Votre colis a quitté le territoire",
	"text034.png": "Plate-forme Briarde",
	"text035.png": "Bureau de Poste Paris",
	"text036.png": "Votre colis est sorti du bureau d'échange. Il est en cours d'acheminement dans le pays de destination",
}
